- name: Налаштування BGInfo
  hosts: all
  tasks:
    - name: Видалення старих ярликів автозапуску
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - "C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Startup/Bginfo.lnk"
        - "C:/Users/{{ ansible_user_id }}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/Bginfo.lnk"

    - name: Видалення записів Bginfo з реєстру (Run keys) через PowerShell
      win_shell: |
        $paths = @("HKCU:\Software\Microsoft\Windows\CurrentVersion\Run", "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run")
        foreach ($path in $paths) {
            Get-ItemProperty -Path $path -ErrorAction SilentlyContinue | Get-Member -MemberType NoteProperty | Where-Object { $_.Name -match "Bginfo" } | ForEach-Object {
                Remove-ItemProperty -Path $path -Name $_.Name -Force
            }
        }

    - name: Створення директорії C:\Sysinternals
      win_file:
        path: C:\Sysinternals
        state: directory

    - name: Завантаження та розпакування BGInfo
      win_unzip:
        src: https://download.sysinternals.com/files/BGInfo.zip
        dest: C:\Sysinternals
        remote_src: yes
        creates: C:\Sysinternals\Bginfo64.exe

    - name: Завантаження файлу конфігурації .bgi
      win_get_url:
        url: https://raw.githubusercontent.com/harmfreem/ansible/main/micros.bgi
        dest: C:\Sysinternals\micros.bgi
        force: yes

    - name: Створення ярлика автозапуску
      win_shortcut:
        src: C:\Sysinternals\Bginfo64.exe
        dest: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Bginfo.lnk
        arguments: '"C:\Sysinternals\micros.bgi" /timer:0 /silent /nolicprompt'
        directory: C:\Sysinternals

    - name: Запуск BGInfo
      win_command: 'C:\Sysinternals\Bginfo64.exe "C:\Sysinternals\micros.bgi" /timer:0 /silent /nolicprompt'
