- name: Оновлення BGInfo
  hosts: all
  gather_facts: false
  tasks:
    - name: Get BGInfo process state
      win_shell: |
        if (Get-Process Bginfo* -ErrorAction SilentlyContinue) { 
            Write-Output "Running" 
        } else { 
            Write-Output "Stopped" 
        }
      register: bg_proc
      changed_when: false

    - name: Kill BGInfo only if running
      win_shell: taskkill /F /IM Bginfo* /T
      when: bg_proc.stdout is defined and "Running" in bg_proc.stdout
      ignore_errors: yes

    - name: Create directory
      win_file:
        path: C:\Sysinternals
        state: directory

    - name: Download BGInfo ZIP
      win_get_url:
        url: https://download.sysinternals.com/files/BGInfo.zip
        dest: C:\Sysinternals\BGInfo.zip
        force: yes

    - name: Unzip BGInfo
      win_unzip:
        src: C:\Sysinternals\BGInfo.zip
        dest: C:\Sysinternals
        remote_src: yes

    - name: Update Config
      win_get_url:
        url: https://raw.githubusercontent.com/harmfreem/ansible/main/micros.bgi
        dest: C:\Sysinternals\micros.bgi
        force: yes

    - name: Update Shortcut
      win_shortcut:
        src: C:\Sysinternals\Bginfo64.exe
        dest: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Bginfo.lnk
        arguments: '"C:\Sysinternals\micros.bgi" /timer:0 /silent /nolicprompt'

    - name: Run BGInfo
      win_shell: 'Start-Process "C:\Sysinternals\Bginfo64.exe" -ArgumentList "`"C:\Sysinternals\micros.bgi`" /timer:0 /silent /nolicprompt"'
