- name: Оновлення фону виключно через BGInfo
  hosts: all
  gather_facts: false
  tasks:
    - name: Kill BGInfo
      win_shell: |
        Get-Process Bginfo* -ErrorAction SilentlyContinue | Stop-Process -Force
      ignore_errors: yes

    - name: Force Apply BGInfo
      win_shell: |
        C:\Sysinternals\Bginfo64.exe C:\Sysinternals\micros.bgi /timer:0 /silent /nolicprompt /i /p

    - name: Create Startup Shortcut
      win_shortcut:
        src: C:\Sysinternals\Bginfo64.exe
        dest: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Bginfo.lnk
        arguments: C:\Sysinternals\micros.bgi /timer:0 /silent /nolicprompt /i
