---
- name: Install and configure Zabbix Agent via winget
  hosts: zabbix
  gather_facts: yes

  vars:
    zabbix_conf_path: "C:\\Program Files\\Zabbix Agent\\zabbix_agentd.conf"
    zabbix_server: "159.69.187.239"

  tasks:

    - name: Install Zabbix Agent using winget
      win_command: >
        winget install --id=Zabbix.ZabbixAgent
        --exact
        --silent
        --accept-package-agreements
        --accept-source-agreements
      args:
        creates: "C:\\Program Files\\Zabbix Agent\\zabbix_agentd.exe"

    - name: Generate Zabbix agent configuration
      win_template:
        src: zabbix_agentd.conf.j2
        dest: "{{ zabbix_conf_path }}"
      notify: Restart Zabbix Agent

    - name: Ensure Zabbix Agent service is started
      win_service:
        name: "Zabbix Agent"
        start_mode: auto
        state: started

  handlers:
    - name: Restart Zabbix Agent
      win_service:
        name: "Zabbix Agent"
        state: restarted
