---
- name: Install Winget with all dependencies on Windows Server 2019
  hosts: windows
  gather_facts: false
  vars:
    temp_dir: "C:\\Temp\\winget"
    vclibs_url: "https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx"
    xaml_nuget_url: "https://www.nuget.org/api/v2/package/Microsoft.UI.Xaml/2.7.3"
    winget_url: "https://aka.ms/getwinget"

  tasks:

    - name: Create temp folder
      win_file:
        path: "{{ temp_dir }}"
        state: directory

    - name: Download Microsoft.VCLibs.x64
      win_get_url:
        url: "{{ vclibs_url }}"
        dest: "{{ temp_dir }}\\Microsoft.VCLibs.x64.14.00.Desktop.appx"

    - name: Download Microsoft.UI.Xaml nupkg
      win_get_url:
        url: "{{ xa
