---
- name: Install Winget (Windows Package Manager)
  hosts: windows # Переконайтеся, що ця назва відповідає вашій групі Windows у inventory
  gather_facts: yes

  vars:
    # URL для останнього стабільного випуску Winget (MSIXBUNDLE) з GitHub.
    # ЗАВЖДИ ПЕРЕВІРЯЙТЕ АКТУАЛЬНІСТЬ ЦЬОГО ПОСИЛАННЯ!
    # Відвідайте: https://github.com/microsoft/winget-cli/releases
    # Шукайте файл з розширенням .msixbundle (наприклад, Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle)
    # Наразі найновіша стабільна версія — 1.10.390. Якщо ви хочете її, використовуйте:
    # "https://github.com/microsoft/winget-cli/releases/download/v1.10.390/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
    #
    # Якщо вам потрібна саме версія 1.7.10861, використовуйте:
    winget_release_url: "https://github.com/microsoft/winget-cli/releases/download/v1.7.10861/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" # <--- ЦЕ ПОСИЛАННЯ НА 1.7.10861
    
    winget_installer_path: "C:\\Windows\\Temp\\Microsoft.DesktopAppInstaller.msixbundle"

  tasks:
    - name: Check if Winget is already installed and accessible
      # Перевіряємо наявність 'winget.exe' у PATH.
      # ignore_errors дозволяє продовжити, навіть якщо команду не знайдено.
      win_shell: "Get-Command winget.exe -ErrorAction SilentlyContinue"
      register: winget_check
      ignore_errors: true

    - name: Download Winget MSIXBUNDLE if not already installed
      # Завантажуємо інсталятор Winget з GitHub.
      # force: no запобігає повторному завантаженню, якщо файл вже існує.
      win_get_url:
        url: "{{ winget_release_url }}"
        dest: "{{ winget_installer_path }}"
        force: no
      when: winget_check.failed # Виконуємо, лише якщо Winget не було знайдено.

    - name: Install Winget using PowerShell (Add-AppxPackage)
      # Встановлюємо пакет MSIXBUNDLE за допомогою Add-AppxPackage.
      # -ForceUpdateFromAnyVersion дозволяє оновити існуючу версію.
      win_shell: |
        Add-AppxPackage -Path "{{ winget_installer_path }}" -ForceUpdateFromAnyVersion
      args:
        executable: powershell.exe
      when: winget_check.failed # Виконуємо, лише якщо Winget не було знайдено.

    - name: Verify Winget installation by checking version
      # Повторно перевіряємо встановлення, отримуючи версію Winget.
      win_shell: "winget --version"
      register: winget_version_check
      changed_when: false # Ця команда не змінює стан системи.
      when: winget_check.failed or winget_version_check.rc != 0

    - name: Display Winget version if successfully installed
      # Виводимо версію Winget, якщо перевірка пройшла успішно.
      ansible.builtin.debug:
        msg: "Winget installed successfully. Version: {{ winget_version_check.stdout | default('N/A') }}"
      when: winget_version_check.rc == 0

    - name: 'Note: Rebooting terminal/session might be required for Winget to be in PATH' # Виправлено синтаксис
      # Нагадування про необхідність перезапуску сесії PowerShell/CMD.
      ansible.builtin.debug:
        msg: "Winget has been installed. You might need to close and reopen your PowerShell/CMD session for 'winget' command to be recognized in PATH."
      when: winget_check.failed # Показуємо це повідомлення, якщо Winget був щойно встановлений.
