---
- name: Install Winget (Windows Package Manager)
  hosts: windows 
  gather_facts: yes

  vars:
    # ... (інші змінні без змін) ...
    
    # URL для фреймворку Microsoft.UI.Xaml.2.8.
    # *** ВАЖЛИВО: ОНОВЛЕНО! ТЕПЕР ЦЕ ПРЯМЕ ПОСИЛАННЯ НА .APPX/.APPXBUNDLE ***
    # Знайдіть його на: https://github.com/microsoft/WindowsAppSDK/releases
    # Це приклад для v1.4.231115001, шукайте актуальний!
    microsoft_ui_xaml_url: "https://github.com/microsoft/WindowsAppSDK/releases/download/v1.4.231115001/Microsoft.UI.Xaml.2.8.appx" 
    microsoft_ui_xaml_path: "C:\\Windows\\Temp\\Microsoft.UI.Xaml.2.8.appx"


  tasks:
    # ... (усі завдання без змін) ...
