---
- name: Install Winget (Windows Package Manager)
  hosts: windows # Переконайтеся, що ця назва відповідає вашій групі Windows у inventory
  gather_facts: yes

  vars:
    # Шлях до файлу Winget MSIXBUNDLE на вашому Ansible-контролері.
    # *** ВАЖЛИВО: ОНОВІТЬ ЦЕЙ ШЛЯХ ***
    # Він повинен вказувати на локальне розташування файлу .msixbundle, який ви ЗАВАНТАЖИЛИ ВРУЧНУ.
    # Наприклад: "/home/ваш_користувач/Downloads/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
    local_winget_installer_src: "/tmp/ansible_downloads/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" # <--- ЗМІНІТЬ ЦЕЙ ШЛЯХ!
    
    winget_installer_path: "C:\\Windows\\Temp\\Microsoft.DesktopAppInstaller.msixbundle"

    # URL для фреймворку Microsoft.UI.Xaml.2.8.
    # *** ВАЖЛИВО: ПЕРЕВІРТЕ ТА ОНОВІТЬ ЦЕЙ ЛІНК, ЯКЩО ПОТРІБНО ***
    # Шукайте на: https://github.com/microsoft/WindowsAppSDK/releases
    microsoft_ui_xaml_url: "https://www.nuget.org/api/v2/package/Microsoft.UI.Xaml/2.8.6" # Це посилання на NuGet, яке перенаправляє на .appx
    # АБО, якщо ви знайдете пряме посилання на .appx/.appxbundle на GitHub (приклад):
    # microsoft_ui_xaml_url: "https://github.com/microsoft/WindowsAppSDK/releases/download/v1.4.231115001/Microsoft.UI.Xaml.2.8.appx"
    microsoft_ui_xaml_path: "C:\\Windows\\Temp\\Microsoft.UI.Xaml.2.8.appx"


  tasks:
    - name: Check if Winget is already installed and accessible
      win_shell: "Get-Command winget.exe -ErrorAction SilentlyContinue"
      register: winget_check
      ignore_errors: true

    - name: Copy Winget MSIXBUNDLE to target if not already installed
      # Модуль win_copy копіює файл з контролера Ansible на цільову машину Windows.
      win_copy:
        src: "{{ local_winget_installer_src }}" # Шлях на контролері Ansible
        dest: "{{ winget_installer_path }}"     # Шлях на цільовій машині Windows
      when: winget_check.failed

    - name: Download Microsoft.UI.Xaml.2.8 framework if needed
      # Цей крок все ще використовує win_get_url, оскільки цей файл ще не завантажувався вручну.
      win_get_url:
        url: "{{ microsoft_ui_xaml_url }}"
        dest: "{{ microsoft_ui_xaml_path }}"
        force: no
      when: winget_check.failed
    
    - name: Install Microsoft.UI.Xaml.2.8 framework
      win_shell: |
        Add-AppxPackage -Path "{{ microsoft_ui_xaml_path }}" -ForceUpdateFromAnyVersion
      args:
        executable: powershell.exe
      when: winget_check.failed

    - name: Install Winget using PowerShell (Add-AppxPackage)
      win_shell: |
        Add-AppxPackage -Path "{{ winget_installer_path }}" -ForceUpdateFromAnyVersion
      args:
        executable: powershell.exe
      when: winget_check.failed

    - name: Verify Winget installation by checking version
      win_shell: "winget --version"
      register: winget_version_check
      changed_when: false
      when: winget_check.failed or winget_version_check.rc != 0

    - name: Display Winget version if successfully installed
      ansible.builtin.debug:
        msg: "Winget installed successfully. Version: {{ winget_version_check.stdout | default('N/A') }}"
      when: winget_version_check.rc == 0

    - name: 'Note: Rebooting terminal/session might be required for Winget to be in PATH'
      ansible.builtin.debug:
        msg: "Winget has been installed. You might need to close and reopen your PowerShell/CMD session for 'winget' command to be recognized in PATH."
      when: winget_check.failed
