---
- name: Install Winget (Windows Package Manager) - Auto Download
  hosts: windows # Переконайтеся, що ця назва відповідає вашій групі Windows у inventory
  gather_facts: yes

  vars:
    # URL для останнього стабільного випуску Winget (MSIXBUNDLE) з GitHub.
    # Залишаємо версію 1.7.10861, як ви просили раніше.
    winget_release_url: "https://github.com/microsoft/winget-cli/releases/download/v1.7.10861/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
    winget_installer_path: "C:\\Windows\\Temp\\Microsoft.DesktopAppInstaller.msixbundle"

    # URL для фреймворку Microsoft.UI.Xaml.2.8 (x64) з GitHub.
    microsoft_ui_xaml_url: "https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx"
    microsoft_ui_xaml_path: "C:\\Windows\\Temp\\Microsoft.UI.Xaml.2.8.x64.appx"

    # *** ОНОВЛЕНО: URL для фреймворку Microsoft.VCLibs.140.00.UWPDesktop ***
    # *** ВАЖЛИВО: ПЕРЕВІРТЕ ЦЕ ПОСИЛАННЯ! ВОНО ПОВИННО ВКАЗУВАТИ НА .APPX-ФАЙЛ ***
    # Спробуйте це:
    microsoft_vclibs_url: "https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx" 
    microsoft_vclibs_path: "C:\\Windows\\Temp\\Microsoft.VCLibs.140.00.UWPDesktop.appx"


  tasks:
    - name: Check if Winget is already installed and accessible
      win_shell: "Get-Command winget.exe -ErrorAction SilentlyContinue"
      register: winget_check
      ignore_errors: true

    - name: Download Winget MSIXBUNDLE if not already installed
      win_get_url:
        url: "{{ winget_release_url }}"
        dest: "{{ winget_installer_path }}"
        force: no
      when: winget_check.failed

    - name: Download Microsoft.VCLibs.140.00.UWPDesktop framework if needed
      # Цей крок завантажить необхідну залежність (VCLibs UWP).
      win_get_url:
        url: "{{ microsoft_vclibs_url }}"
        dest: "{{ microsoft_vclibs_path }}"
        force: no
      when: winget_check.failed
    
    - name: Install Microsoft.VCLibs.140.00.UWPDesktop framework
      win_shell: |
        Add-AppxPackage -Path "{{ microsoft_vclibs_path }}" -ForceUpdateFromAnyVersion
      args:
        executable: powershell.exe
      when: winget_check.failed

    - name: Download Microsoft.UI.Xaml.2.8 framework if needed
      win_get_url:
        url: "{{ microsoft_ui_xaml_url }}"
        dest: "{{ microsoft_ui_xaml_path }}"
        force: no
      when: winget_check.failed
    
    - name: Install Microsoft.UI.Xaml.2.8 framework
      win_shell: |
        Add-AppxPackage -Path "{{ microsoft_ui_xaml_path }}" -ForceUpdateFromAnyVersion
      args:
        executable: powershell.exe
      when: winget_check.failed

    - name: Install Winget using PowerShell (Add-AppxPackage)
      win_shell: |
        Add-AppxPackage -Path "{{ winget_installer_path }}" -ForceUpdateFromAnyVersion
      args:
        executable: powershell.exe
      when: winget_check.failed

    - name: Verify Winget installation by checking version
      win_shell: "winget --version"
      register: winget_version_check
      changed_when: false
      when: winget_check.failed or winget_version_check.rc != 0

    - name: Display Winget version if successfully installed
      ansible.builtin.debug:
        msg: "Winget installed successfully. Version: {{ winget_version_check.stdout | default('N/A') }}"
      when: winget_version_check.rc == 0

    - name: 'Note: Rebooting terminal/session might be required for Winget to be in PATH'
      ansible.builtin.debug:
        msg: "Winget has been installed. You might need to close and reopen your PowerShell/CMD session for 'winget' command to be recognized in PATH."
      when: winget_check.failed
