- name: Get RouterOS Version
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Get clean version string
      community.network.routeros_command:
        commands: /system resource get version
      register: output

    - name: Print version
      debug:
        var: output
