- name: Get RouterOS Version
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Get clean version string
      community.network.routeros_command:
        commands: /system resource print value-list
      register: output

    - name: Print version
      debug:
        msg: "{{ output.stdout_lines[0] | select('search', 'version:') | map('regex_replace', 'version: ', '') | first }}"
