---
- name: Test WinRM connection
  hosts: SkylansStrong
  gather_facts: no
  vars:
    ansible_user: "{{ win_user }}"
    ansible_password: "{{ win_pass }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Debug user
      debug:
        msg: "Connecting as user {{ ansible_user }}"

    - name: Test WinRM ping
      win_ping:
