---
- name: Update all apps via Winget
  hosts: all
  gather_facts: no

  tasks:
    - name: Update all installed apps (auto-yes)
      ansible.windows.win_shell: |
        winget upgrade --all --accept-package-agreements --accept-source-agreements --silent
      register: winget_update

    - name: Show update output
      ansible.builtin.debug:
        var: winget_update.stdout_lines
