- name: Update apps with service management
  hosts: all
  gather_facts: no
  tasks:
    - name: Check and stop Zabbix service
      ansible.windows.win_service:
        name: "Zabbix Agent"
        state: stopped
      register: zabbix_stop
      ignore_errors: yes

    - name: Update all packages via Winget
      ansible.windows.win_shell: |
        winget upgrade --all --accept-package-agreements --accept-source-agreements --silent
      register: winget_update
      failed_when: winget_update.rc != 0

    - name: Start Zabbix service
      ansible.windows.win_service:
        name: "Zabbix Agent"
        state: started
      when: zabbix_stop is succeeded
