- name: Update apps with Zabbix 2 management
  hosts: all
  gather_facts: no
  tasks:
    - name: Get service info
      ansible.windows.win_service_info:
        name: "Zabbix Agent 2"
      register: service_info

    - name: Stop Zabbix Agent 2
      ansible.windows.win_service:
        name: "Zabbix Agent 2"
        state: stopped
      when: service_info.exists

    - name: Update Zabbix Agent 2
      ansible.windows.win_shell: |
        $id = "Zabbix.ZabbixAgent2"
        if (winget list --id $id --exact) {
            winget upgrade --id $id --exact --override "REINSTALLMODE=amus" --accept-package-agreements --accept-source-agreements --silent
        }
      failed_when: false

    - name: Update all other packages
      ansible.windows.win_shell: winget upgrade --all --accept-package-agreements --accept-source-agreements --silent
      failed_when: false

    - name: Start Zabbix Agent 2
      ansible.windows.win_service:
        name: "Zabbix Agent 2"
        state: started
      when: service_info.exists
