---
- name: Windows Update without reboot
  hosts: windows
  gather_facts: no
 

  tasks:
    - name: Ensure Windows Update policy allows installation
      win_regedit:
        path: HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AUOptions
        data: 4
        type: dword
        state: present

    - name: Restart Windows Update service
      win_service:
        name: wuauserv
        state: restarted

    - name: Search for available updates
      win_updates:
        state: searched
      register: update_search

    - name: Show available updates
      debug:
        var: update_search.updates

    - name: Install all available updates (no reboot)
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
        reboot: no
      register: update_install

    - name: Show installation summary
      debug:
        msg: >
          Installed {{ update_install.installed_update_count }} updates.
          Reboot required: {{ update_install.reboot_required }}
