- name: Дозволити Ansible ставити оновлення
  hosts: windows
  gather_facts: no
  tasks:
    - name: Змінити політику автооновлення
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AUOptions
        data: 4
        type: dword

    - name: Перезапуск служби Windows Update
      win_service:
        name: wuauserv
        state: restarted

    - name: Встановити всі оновлення
      win_updates:
        state: installed
        reboot: yes
